services:
  nginx:
    image: nginx:1.25
    ports:
      - "1243:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
    networks:
      - vita
    restart: unless-stopped

  php:
    image: php:7.4-fpm
    volumes:
      - .:/var/local/sandboxes/dev/www
    environment:
      PHP_FPM_LISTEN: "0.0.0.0:9000"
    healthcheck:
      test: ["CMD", "pidof", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - vita
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - vita
    restart: unless-stopped

networks:
  vita:
    driver: bridge
